development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: original_app_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: original_app_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password:
  host: localhost
